name: Build Linux (Manual)

on:
  workflow_dispatch:

env:
  FREE_DISKSPACE: |
    sudo rm -rf /usr/local/.ghcup 2>/dev/null || true
    sudo rm -rf /usr/share/dotnet 2>/dev/null || true
    sudo rm -rf /usr/share/swift 2>/dev/null || true
    sudo rm -rf /usr/share/miniconda 2>/dev/null || true

jobs:
  build-linux-static:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: free up diskspace
      run: ${{env.FREE_DISKSPACE}}

    - name: prepare build environment
      uses: ./.github/actions/build-docker
      with:
        dockerfile: Dockerfile.linux
        image: salvium:build-env-linux
        cache-scope: gui-deps-linux
        threads: 3

    - name: build
      run: docker run --rm --user "$(id -u):$(id -g)" -e HOME=/tmp -e USE_DEVICE_TREZOR_MANDATORY=ON -v "${{ github.workspace }}:/salvium-gui" -w /salvium-gui salvium:build-env-linux sh -c 'make release-static -j3'

    - name: sha256sum
      run: shasum -a256 ${{ github.workspace }}/build/release/bin/salvium-wallet-gui

    - name: test qml
      run: sh .github/test-qml-linux.sh

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.job }}
        path: |
          ${{ github.workspace }}/build/release/bin/salvium-wallet-gui
          ${{ github.workspace }}/build/release/bin/salviumd
